### PR TITLE
H5py-like interface

### PR DESCRIPTION
**Pull request by clbarnes**
~~Not ready for merge yet, depends on #64~~ Transposes like z5

~~N.B. h5py_like depends on python 3.7. I'll take a look through it and see what I'd lose to drop down to 3.6. However, 3.5 would probably be an issue.~~ Compatible with 3.6+

### CODE REVIEW

**Comment by clbarnes** [comment]
The h5py-like interface already handles all the transposes it needs to to match z5, I think. Still figuring out how to test that, though.

**Comment by clbarnes** [comment]
Got some tests around block ordering now. Sigh, time to make a conda env to test against that.

**Comment by clbarnes** [comment]
Tests show an array created by z5 can be read by pyn5's h5py-like interface and get the same data back, and vice versa!

Weirdly the hashsum of the blocks is not the same, even when the compression arguments are the same and the two implementations can read each other's creations.

**Comment by aschampion** [comment]
Great!

> Weirdly the hashsum of the blocks is not the same, even when the compression arguments are the same and the two implementations can read each other's creations.

It looks like you're hashing the files directly, which would depend on things in the gzip, etc. Could the compression be configurable here so raw can be used to removed that variable for inspection? Also, doesn't z5 use a different array ordering, so the hashes would be different anyway?

**Comment by clbarnes** [comment]
Yeah I thought it might be something about the gzip header. I don't think that z5 uses different array ordering - if it did, wouldn't it not be compatible with other implementations?

Configurable compression is definitely something pyn5 could use.

I also checked that both pyn5 and z5 can read the 01118 volume (exported through jython-imglib-N5), and get identical results back.

**Comment by clbarnes** [comment]
When you've got a minute @pattonw , would you mind taking a look at the travis build? It doesn't seem to be working at all but I'm pretty sure I haven't touched any rust or travis stuff since it last worked.

**Comment by pattonw** [comment]
Yeah, I noticed that it was being strange and am looking at it now

**Comment by aschampion** [comment]
Did raw compression resolve the digest difference?

**Comment by clbarnes** [comment]
Haven't tried it yet, will give it a go shortly.

**Comment by clbarnes** [comment]
Yes, hashsums are the same under raw compression using the h5py-like interface.

**Comment by aschampion** [comment]
Awesome, thanks for putting this together so everything is tested.

**Comment by clbarnes** [comment]
And python 3.6 compatiiblity (with `h5py_like>=0.4.0`). I can't go down to 3.5 without major effort, there's a bunch of weirdness around the way Path objects are used, and they are really helpful.

The tests against z5 won't run on CI because that would necessitate installing conda etc., but they can be run locally. When using the raw pyn5 functions, the tests assert that the dimension ordering and block files are **not** the same as z5's, because they do not do the transpositions that z5 does. When using the h5py-like interface, the tests assert that the dimension ordering and block files **are** the same, because it does do those transpositions. I'm fine leaving the API this way (may be worth documenting it) - the rust side reflects the rust-n5 behaviour, which reflects the java behaviour (column-major block indexing). The pythonic interface reflects expected python behaviour (row-major block indexing).

**Comment by clbarnes** [comment]
Added threading, from the python side. By default, reads and writes happen on-thread in serial; datasets have a `threads` attribute which you can set to something truthy to make it do concurrent IO. I don't know what the overhead is for that is, but it involves a bit of currying, starting up a thread pool and so on so it may only help for fairly large writes.

If you want all your datasets to be concurrent, you can set `Dataset.threads`; instances take a copy of that when they're instantiated (so you can't change existing instances' behaviour by mutating the class).

**Comment by clbarnes** [comment]
If you're happy with the python 3.6 dependency, it'd be great if this could go in; got a few requirements files I could simplify.

**Comment by pattonw** [comment]
Oh yeah, this can get merged. I should probably bump the version number and re-release it on pypi. I'll merge it now, and handle the other stuff soon

**Comment by clbarnes** [comment]
Actually just about to push a couple of changes to h5py_like so hold off on the release until I propagate them down to pyn5 too; I'll let you know.

**Pull request merged**
