### PR TITLE
Python 3.9

### PR DESCRIPTION
**Pull request by clbarnes**
Also bump the dependencies.

### CODE REVIEW

**Comment by pattonw** [comment]
Thanks Chris. Im not sure why it's not compiling properly for travis. I'm on a road trip at the moment though so I probably won't be able to look at it for a while.

**Comment by clbarnes** [comment]
No worries, have a good time! I remember seeing something about musl in some maturin release notes, I'll track it down at some point; might be a different version missing from the environment. I'm mainly using GitHub actions now, saves a fair bit of complexity.

**Comment by aschampion** [comment]
Thanks @clbarnes! The only problem was a maturin bug with musl that's been fixed since 0.10.0.

**Comment by clbarnes** [comment]
Ah, good to know it was on maturin's end; I confess I bumped the deps and then didn't look much further into it when it didn't pass.

**Pull request merged**
