### PR TITLE
Bump compiler

### LINKED ISSUE #93: Issue with reading n5 array
* pyn5 version: 1.0.0
* Python version: 3.7.3 
* Operating System: Linux

### Description

I get an exception when reading a n5 file that I just created with pyn5

### What I Did

First create an n5
```
import pyn5
import numpy as np

root = "test.n5"
dataset = "test"
dtype = "UINT8"
dataset_size = [10, 10, 10]
block_size = [2, 2, 2]

pyn5.create_dataset(root, dataset, dataset_size, block_size, dtype)
n5 = pyn5.open(root, dataset, dtype, False)

pyn5.write(
    n5,
    (np.array([0, 0, 0]), np.array(dataset_size)),
    np.ones(dataset_size),
)
```
Then, in a new Python session, read the file
```
import pyn5
import numpy as np
n5 = pyn5.open("test.n5", 'test', "UINT8", True)
arr = pyn5.read(n5, ( np.array([0,0,0]), np.array([5,5,5]) ), dtype=np.uint8 )
```
I get the traceback
```
thread '<unnamed>' panicked at 'An error occurred while initializing class SliceBox', /home/pattonw/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.7.0/src/type_object.rs:260:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by clbarnes**
Resolves #93 

- Updates docs to reflect maturin usage
- Bumps versions of pyo3 and numpy(rust)
- Uses the oldest pyo3-compatible compiler
- Travis tests against release builds

### CODE REVIEW

**Comment by pattonw** [comment]
awesome, thanks for figuring this out Chris. It looks like the pyo3 and numpy are being updated quickly so hopefully we won't be stuck with nightly for too long.

**Comment by clbarnes** [comment]
The nightly requirement is unfortunately blocked by a rust feature with no timeline for stabilisation (I linked the tracking issue in #93).

**Comment by pattonw** [comment]
This all looks pretty good to me, can I go ahead and merge it?

**Comment by clbarnes** [comment]
Yep! I don't think there's anything else to change in the docs right now.

**Comment by pattonw** [comment]
Yeah, the deploy stage still isn't running, but I can try to sort that out later

**Pull request merged**
