### PR TITLE
Add py38

### PR DESCRIPTION
**Pull request by clbarnes**
Let's take a punt and see if this build works...

### CODE REVIEW

**Comment by aschampion** [comment]
I think there's some error with n5 putting a double `}` in the root attributes (the "trailing character" error). I noticed this on a local dataset but just thought it was a typo when I'd mucked with the file at some point.

**Comment by clbarnes** [comment]
Well, at least it's promising that it gets that far... Is that on the rust-n5 side?

**Comment by aschampion** [comment]
Yeah, rust-n5.

Gonna guess it was the fix in 5249e2f48800d9f7998903cb696d81652def2d3d causing the version attribute to actually get updated by `open_or_create`->`set_attribute` now, with the buffer being rewound then written to but the file not being truncated, so the old trailing stuff sticks around? I should write better tests for the attributes methods.

**Comment by aschampion** [comment]
That must be it. It'll take me an hour or two to fix this right. Will probably release this as 0.6.1 even though it will technically change the return type of `DefaultBlockWriter::write_block` which is public and therefore breaking.

**Comment by clbarnes** [comment]
Not urgent, so don't let it interrupt you!

**Comment by aschampion** [comment]
Fixed, published and merged here, see if that sorts it.

Quite a bad error, and annoyingly also a similar error with dangling block data that I'd anticipated before but tested in a stupid way so thought it wasn't an issue. After having written some tests for the attributes APIs I'll also want to revisit them (both for n5 and big chunkus) because they aren't adequate as is.

**Comment by aschampion** [comment]
Passes now. Looks like there's a slight different set of changes in #109, though.

**Comment by clbarnes** [comment]
Huh, I'd forgotten I made that PR, there was quite a lag between the py38 release and the h5py wheels being deployed. Looks like October me, flushed with the vigour of youth, was more thorough.

**Comment by clbarnes** [comment]
Closing in favour of #136

**Pull request closed without merging**
